[build.env]
passthrough = [
  "RUST_BACKTRACE",
  "RUST_LOG",
  "MMAL_LIB_DIR",
  "MMAL_INCLUDE_DIR"
]

# Raspberry Pi 3
[target.armv7-unknown-linux-gnueabihf]
image = "vvv/armv7-unknown-linux-gnueabihf:1.20190925"

# Raspberry Pi Zero
[target.arm-unknown-linux-gnueabihf]
image = "vvv/arm-unknown-linux-gnueabihf:1.20230405"